### ISSUE TITLE
Upload PDST file with acceleration data

### ISSUE THREAD

**Issue by PieterjanVerhelst** [PieterjanVerhelst/eel-pdst-analysis#29]
The current 'pdst_raw_to_tidy.R' code uses datasets with two datablocks: temperature and depth. I know want to include files with an extra datablock being acceleration. Hence, the script needs to be adapted to also store these data in the daylog and sensorlog files. Example data on request.

**Comment by damianooldoni** [comment]
Yes, this is surely possible. Please send a file here. I started a INBO repo, [archivaltag](https://github.com/inbo/archivaltag), containing  an R package called as the repo. Both repo and R pacakge could be named differently later. Reading these type of data will be implemented there.

**Comment by damianooldoni** [comment]
@PieterjanVerhelst: please, provide me a file with such kind of data and I will work on it 👍

**Comment by PieterjanVerhelst** [comment]
@damianooldoni this is the file I shared in our gmail chat. File is too large to share.

**Comment by damianooldoni** [comment]
Yes, I got it already yesterday, sorry to ask it again. For my information: the file is called `A15881_04-09-2020.csv`.

**Comment by damianooldoni** [comment]
Hi 👋 
I worked on this in branch [improve-reading-functionality](https://github.com/PieterjanVerhelst/eel-pdst-analysis/tree/improve-reading-functionality).
I will start a PR if you agree. Should the PR point to `main` or `dvm-analysis`?

**Comment by PieterjanVerhelst** [comment]
@damianooldoni I will test asap! You can can do the PR to `dvm-analysis`.

**Comment by PieterjanVerhelst** [comment]
This issue has been solved by merging the PR #30 .
